In [1]:
import pandas as pd

print(pd.__version__)

3.0.5

In [2]:
filename = "finalized.csv"

df = pd.read_csv(filename, encoding="ISO-8859-1")

In [3]:
type(df)

pandas.DataFrame

In [4]:
df.head()

,Title,Release Year,Distributor,Production,Longitude,Latitude
0,Chance Season 2,2017.0,Hulu,TVM Productions Inc.,-122.405822,37.802395
1,Red Widow,2013.0,American Broadcasting Company (ABC),Beyond Pix,-122.411031,37.792781
2,A Taiwanese Tale of Two Cities,2018.0,Netflix,Envision Productions Inc.,-122.396034,37.798070
3,Americana,2015.0,NaN,Sutro Films LLC,-122.448423,37.802931
4,DEVS,2020.0,FX Network,Minim Productions,-122.417619,37.800359

In [5]:
df.shape

(2127, 6)

In [6]:
df.tail()

,Title,Release Year,Distributor,Production,Longitude,Latitude
2122,Nora Prentiss,1947.0,Warner Bros. Pictures,Warner Bros. Pictures,-122.413322,37.788455
2123,Ant-Man and the Wasp,2018.0,Walt Disney Studios Motion Pictures,"PYM Particles Productions II, LLC",-122.414910,37.795960
2124,Venom,2018.0,"Columbia Pictures, Sony Pictures Releasing","L.O.Z. Productions, Inc.",-122.410246,37.800775
2125,Looking Season 2 ep 206,2015.0,HBO,"Mission Street Productions, LLC",-122.434890,37.771831
2126,Dope Queens,2025.0,TBD,TomorrowLand Productions Co Inc.,-122.416134,37.752482

In [7]:
df.dtypes

Title               str
Release Year    float64
Distributor         str
Production          str
Longitude       float64
Latitude        float64
dtype: object

In [8]:
df.columns

Index(['Title', 'Release Year', 'Distributor', 'Production', 'Longitude',
       'Latitude'],
      dtype='str')

In [9]:
df.info

<bound method DataFrame.info of                                Title  Release Year  \
0                    Chance Season 2        2017.0
1                          Red Widow        2013.0
2     A Taiwanese Tale of Two Cities        2018.0
3                          Americana        2015.0
4                               DEVS        2020.0
...                              ...           ...
2122                   Nora Prentiss        1947.0
2123            Ant-Man and the Wasp        2018.0
2124                           Venom        2018.0
2125         Looking Season 2 ep 206        2015.0
2126                     Dope Queens        2025.0

                                     Distributor  \
0                                           Hulu
1            American Broadcasting Company (ABC)
2                                        Netflix
3                                            NaN
4                                     FX Network
...                                          ...
2122                       Warner Bros. Pictures
2123         Walt Disney Studios Motion Pictures
2124  Columbia Pictures, Sony Pictures Releasing
2125                                         HBO
2126                                         TBD

                             Production   Longitude   Latitude
0                  TVM Productions Inc. -122.405822  37.802395
1                            Beyond Pix -122.411031  37.792781
2             Envision Productions Inc. -122.396034  37.798070
3                       Sutro Films LLC -122.448423  37.802931
4                     Minim Productions -122.417619  37.800359
...                                 ...         ...        ...
2122              Warner Bros. Pictures -122.413322  37.788455
2123  PYM Particles Productions II, LLC -122.414910  37.795960
2124           L.O.Z. Productions, Inc. -122.410246  37.800775
2125    Mission Street Productions, LLC -122.434890  37.771831
2126   TomorrowLand Productions Co Inc. -122.416134  37.752482

[2127 rows x 6 columns]>

In [18]:
mask = df["Title"].str.startswith("T", na=False)

df2 = df[mask]
df2

,Title,Release Year,Distributor,Production,Longitude,Latitude
8,The Wedding Planner,2001.0,Sony Pictures Entertainment,Columbia Pictures,-122.411414,37.785667
10,Time After Time,1979.0,Columbia Broadcasting System (CBS),Orion Pictures Corp.,-122.402171,37.792255
11,Terminator - Genisys,2015.0,Paramount Pictures,T5 Productions LLC,-122.414136,37.791429
38,The Presidio,1988.0,Paramount Pictures,Paramount Pictures,-122.405822,37.802395
43,Terminator - Genisys,2015.0,Paramount Pictures,T5 Productions LLC,-122.394820,37.794177
...,...,...,...,...,...,...
2087,The Dead Pool,1988.0,Warner Bros. Pictures,Warner Bros. Pictures,-122.398955,37.757231
2094,The OA Part II,2019.0,Netflix,Lunar Mining LLC,-122.455615,37.788908
2099,The Dead Pool,1988.0,Warner Bros. Pictures,Warner Bros. Pictures,-122.435281,37.779150
2115,The Love Bug,1968.0,Buena Vista Distribution,Walt Disney Productions,-122.403378,37.804043
2119,The Enforcer,1976.0,Warner Bros. Pictures,Warner Bros. Pictures,-122.417534,37.753918